### Sign in as an existing user (admin)
POST http://localhost:3000/auth/login
Content-Type: application/json

{
  "username": "admin",
  "password": "admin"
}

### Sign in as an existing user (normal)
POST http://localhost:3000/auth/login
Content-Type: application/json

{
  "username": "normal",
  "password": "normal"
}

### Sign in as an existing user (limited)
POST http://localhost:3000/auth/login
Content-Type: application/json

{
  "username": "limited",
  "password": "limited"
}


@token = response.body.access_token
### Get the /locus endpoint using the limited token
GET http://localhost:3000/locus
Authorization: Bearer {{token}}

