### Sign in as an existing user (admin)
POST http://localhost:3000/auth/login
Content-Type: application/json

{
  "username": "admin",
  "password": "admin"
}

### Sign in as an existing user (normal)
POST http://localhost:3000/auth/login
Content-Type: application/json

{
  "username": "normal",
  "password": "normal"
}

### Sign in as an existing user (limited)
POST http://localhost:3000/auth/login
Content-Type: application/json

{
  "username": "limited",
  "password": "limited"
}

### Get /locus as Admin (all data)
GET http://localhost:3000/locus
Authorization: Bearer {{response.body.access_token}}

### Get /locus as Admin (with sideloading)
GET http://localhost:3000/locus?sideloading=locusMembers
Authorization: Bearer {{response.body.access_token}}

### Get /locus as Normal User (limited columns)
GET http://localhost:3000/locus
Authorization: Bearer {{response.body.access_token}}

### Get /locus as Normal User (with sideloading - should be ignored)
GET http://localhost:3000/locus?sideloading=locusMembers
Authorization: Bearer {{response.body.access_token}}

### Get /locus as Limited User (allowed regionIds)
GET http://localhost:3000/locus
Authorization: Bearer {{response.body.access_token}}

### Get /locus without token (Unauthorized)
GET http://localhost:3000/locus